### ISSUE TITLE
Sending click event while dragging

### ISSUE THREAD

**Issue by GitKokoszka** [transcriptic/react-map-interaction#37]
Yo Scott. First of all I wanna say I loved this module. 

I was waiting for some days when you will fix the mobile device click problem from another issue and it's finally there! But there is another problem that came out now which had not been there before. When you drag around some clickable element on your desktop and you pull finger up in the same spot or elsewhere, it doesn't really matter, it instantly activates the click event. I suppose it is not the wanted feature. I'm sure you will be able to reproduce the problem. Cheers!

**Comment by scottyantipa** [comment]
Hey @GitKokoszka thank you!

You're right that the fix did change the default behavior, but you should be able to get around this using the instructions here: https://github.com/transcriptic/react-map-interaction/blob/master/README.md#click-and-drag-handlers-on-child-elements

MapInteraction will now tell you if the element was click vs dragged by calling `preventDefault` on the click event, and your component can then determine if it wants to respond to the drag end or the click/touch end.

I know this isn't an ideal solution. But it's a tough situation and I'm not sure if there's a better api. Handling dom click and touch events is tough. I was previously trying to handle this by stopping propagation, but this caused other bugs that didn't have obvious fixes.

**Comment by MathieuLoutre** [comment]
Using `defaultPrevented` is elegant and versatile enough for my use case so thank you for putting that in! Do you think there might be a way to add a threshold for it so that it can allow for a tiny bit of movement? When using a trackpad sometimes the click makes me map move by a tiny amount (invisible but it does trigger defaultPrevented) and it feels like the click is not working (but the handler is called correctly). Being able to set a tolerance would be great.

I'd be happy to look into a PR for this, if you had any pointers as I'm unfamiliar with the codebase at the moment.

**Comment by MathieuLoutre** [comment]
Hi @scottyantipa! Just to say I've put together a PR (#54) which adds a new prop to manage the threshold. Would love for you to take a look :)

**Comment by scottyantipa** [comment]
@MathieuLoutre I see, and agree its a problem.

We used to do something to guard against this
https://github.com/transcriptic/react-map-interaction/blob/3dce65442032c21a863e7ad587a4e59e7a79fbaf/src/MapInteraction.jsx#L219

I guess that got dropped somewhere. Let's follow up on your PR.

**Comment by scottyantipa** [comment]
Fixed in #54 

I'll ping here one a fix is released.

**Comment by scottyantipa** [comment]
Published in react-map-interaction@1.3.3
